### ISSUE TITLE
Form

### ISSUE THREAD

**Issue by radogado** [radogado/niui#5]
- ~~Conditional sections~~
- ~~dragging a file over a "file" input~~
- ~~IE8 file input style~~
- ~~IE8, 9 select~~
- ~~Flat layout version~~
- ~~Outline effect is cut out on the right; missing on Checkbox, Select, File inputs.~~
- ~~Dynamic form submit without page reload (JS only/PHP)~~
- Drop down with search field filter – datalist element?
- ~~Tab key skips checkbox~~
- ~~WebKit: Flat form file text moving up when focused by tab key~~
- ~~Baseline mis-alignment (fix with calc/Sass)~~
- ~~File drop not working~~
- ~~Dynamic form not working in WordPress~~

**Comment by mklopets** [comment]
![image](https://cloud.githubusercontent.com/assets/3150328/8392831/6115e130-1d00-11e5-994c-96cdd52545b5.png)
The radio button dot doesn't seem to be centre-aligned on the vertical axis (Chrome 43)

**Comment by radogado** [comment]
Thank you @mklopets I'll fix it when time allows. Regards.
